name: Global Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Auto-Locate and Build
        run: |
          # البحث عن مكان ملف البناء الفعلي
          GRADLE_PATH=$(find . -name "build.gradle" | head -n 1)
          PROJECT_ROOT=$(dirname "$GRADLE_PATH")
          echo "Found project at: $PROJECT_ROOT"
          cd "$PROJECT_ROOT"
          
          # إجبار النظام على إنشاء ملفات التشغيل
          gradle wrapper --gradle-version 8.2
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon

      - name: Export
        uses: actions/upload-artifact@v4
        with:
          name: App-Ready
          path: "**/*.apk"
