name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build
        run: |
          # الدخول للمجلد الذي يحتوي على الكود
          cd SecretVault-Android
          
          # التأكد من وجود ملف الإعدادات
          if [ ! -f "settings.gradle" ]; then echo "include ':app'" > settings.gradle; fi
          
          # بناء الملفات الضرورية والبدء
          gradle wrapper
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Done
        uses: actions/upload-artifact@v4
        with:
          name: AppFile
          path: "**/*.apk"
